sudo: required
language: python
dist: trusty
before_install:
  - sudo apt-get -qq update
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install --upgrade pip
  - pip install .
  - python -c "import nltk; nltk.download(['stopwords', 'punkt'])"
script:
  - python -m unittest
branches:
  only:
    - master
    - dev
