name: qbmd
dependencies:
  - python=3.6.5
  - jupyter=1.0.0
  - pylint
  - rope
  - beautifulsoup4=4.6.3
  - numpy=1.15.3
  - nltk=3.3.0
  - pandas=0.23.4
  - pip:
    - 'git+https://github.com/tagucci/pythonrouge.git'

    